Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Fernanda
// Descrição   : estrutura de repetição ENQUANTO
// Autor(a)    : Henrique Jose Godoy
// Data atual  : 11/12/2024
Var
// Seção de Declarações das variáveis 
i, resultado: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
i := 1
enquanto i <= 10 faca
resultado := 8 * i
escreval("8 x ", i, " = ", resultado)
i := i + 1
fimenquanto
Fimalgoritmo